name: SelfRunnerTesting
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
 
    runs-on: win100
 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -q test -DsuiteName="testsuites\login.xml" -Dbrowser="chrome"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./public
